version: '3.9'

x-common-env: &common-env
  environment:
    MONGO_URL: mongodb://mongo:27017/qa_portfolio
  depends_on:
    - mongo

services:
  # ðŸ§© MongoDB 
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: qa_portfolio

  # ðŸ§ª Playwright Tests (TypeScript)
  playwright_ts:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: playwright_ts
    env_file:
      - ./.env
    environment:
      MONGO_URL: mongodb://mongo:27017/qa_portfolio
    depends_on:
      - mongo
    ports:
      - "8081:8081"  
    shm_size: 1gb
    volumes:
      - ./playwright_ts:/work/playwright_ts
    command: ["sleep", "infinity"]  

volumes:
  mongo_data:
