version: '3.9'

x-common-env: &common-env
  environment:
    MONGO_URL: mongodb://mongo:27017/qa_portfolio
  depends_on:
    - mongo

services:
  # ðŸ§© MongoDB 
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: qa_portfolio

  # ðŸ§ª Playwright Tests (TypeScript)
  playwright_ts:
    build:
      context: .
      dockerfile: ./Dockerfile
    <<: *common-env
    env_file:
      - ./.env
    command: ["sleep", "infinity"]
    shm_size: 1gb
    container_name: playwright_ts
    volumes:
      - ./playwright_ts:/work/playwright_ts
      - ./playwright_ts/allure-results:/work/playwright_ts/allure-results
      - ./playwright_ts/allure-report:/work/playwright_ts/allure-report

  # ðŸ Playwright Tests (Python)
  playwright_py:
    build:
      context: ./playwright_py 
      dockerfile: ./Dockerfile
    <<: *common-env
    command: ["sleep", "infinity"]
    shm_size: 1gb
    container_name: playwright_py
    volumes:
      - ./playwright_py:/work/playwright_py

volumes:
  mongo_data:
